server {
    listen 80;
    server_name _;
    absolute_redirect off;

    location /guru/ {
        alias /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/index.html /guru/index.html;
    }

    location = /guru {
        return 301 /guru/;
    }

    location / {
        return 404;
    }
}
